FROM nginx

RUN apt update
RUN apt install -y git

RUN rm -rf /var/www/html
RUN git clone https://github.com/AlexViki/appToDoList.git /var/www/html/

COPY nginx_app.conf /etc/nginx/sites-available/default
COPY nginx_htpasswd /etc/nginx/.htpasswd
#COPY start.sh /start.sh

#RUN chmod 0777 /start.sh
#CMD ["/start.sh"]