FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y git nginx

RUN rm -rf /var/www/html
RUN git clone https://github.com/AlexViki/appToDoList.git /var/www/html/

COPY nginx.conf /etc/nginx/sites-available/default
COPY nginx_htpasswd /etc/nginx/.htpasswd
COPY start.sh /start.sh

RUN chmod 0777 /start.sh
#CMD ["/start.sh"]