FROM ubuntu:18.04

RUN apt-get -y update
RUN apt-get -y install nginx

RUN echo 'Hello World from Docker!' > /var/www/html/index.html


CMD ["/usr/sbin/apache2ctl", "-D","FOREGROUND"]

RUN service nginx restart

EXPOSE 80