FROM ubuntu:18.04

RUN apt-get -y update && apt-get -y install nginx && apt-get -y install git

#RUN git -C /var/www/html clone https://github.com/AlexViki/appToDoList.git

#RUN echo 'Hello World from Docker!' > /var/www/html/index.html

RUN service nginx restart

EXPOSE 80